DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS app;


CREATE TABLE user(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE app
(

    id INTEGER PRIMARY KEY AUTOINCREMENT,
    
);